baseURL = 'https://shawnstrick.land/'
languageCode = 'en-us'
title = 'Shawn Strickland'
theme = 'ananke2'

sectionPagesMenu = 'main'

[params]
  env = 'production'

[services]
  [services.googleAnalytics]
    ID = 'G-WGQCJ056H8'

[deployment]
  [[deployment.targets]]
  # An arbitrary name for this target.
  name = "production"
  # Amazon Web Services S3; see https://gocloud.dev/howto/blob/#s3
  # For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
  URL = "s3://shawn-strickland-public-site?region=us-east-1"